### ISSUE TITLE
Error on version 1.0.2 on M1 Mac

### ISSUE THREAD

**Issue by bgajdero** [peytoncasper/remarkable-sidekick#5]
The error I'm getting
Uncaught Exception:
TypeError: Object has been destroyed
at sendError (/Applications/Remarkable Sidekick.app/Contents/Resources/app.asar/build/main.bundle.js:28184:26)
at updateStatus (/Applications/Remarkable Sidekick.app/Contents/Resources/app.asar/build/main.bundle.js:27599:74)
at Client.disconnect (/Applications/Remarkable Sidekick.app/Contents/Resources/app.asar/build/main.bundle.js:27587:5)
at Client.emit (events.js:315:20)
at Timeout.sendKA (/Applications/Remarkable Sidekick.app/Contents/Resources/app.asar/build/main.bundle.js:11051:16)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)

**Comment by peytoncasper** [comment]
Interesting, I've seen this pop up when something is causing the app to shutdown in the middle of sending an IPC message. In this case, it looks like its crashing/shutting down in the middle of sending an error to the frontend. 
An item on my list is to improve the debug logging and then I would love to grab a log file from you if you're open to it.

**Comment by bgajdero** [comment]
Sure. Where can I grab it?

**Comment by peytoncasper** [comment]
Should be at this path. 

/System/Volumes/Data/Users/$USER/Library/Application Support/remarkable-sidekick/main.log

**Comment by bgajdero** [comment]
[main_show.log](https://github.com/peytoncasper/remarkable-sidekick/files/8081451/main_show.log)
