### ISSUE TITLE
Error when replacing sleep screen on Mac 

### ISSUE THREAD

**Issue by lasergoat** [peytoncasper/remarkable-sidekick#8]
**Version:** Version 1.0.2 (1.0.2)

Repro Steps:

installed dmg from releases page
configured connection with USB
connected
go to Images tab
Drag in new image (attached actual image file png below)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/15964/154310088-4584508a-aa1d-48a9-b409-0a2ee2643110.png">

```
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/me/Library/Application Support/remarkable-sidekick/local_images/raptor-engine-rm2-sleep-screen.png'
at Object.openSync (fs.js:476:3)
at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
at Object.writeFileSync (fs.js:1467:35)
at handleChangeLockscreen (/Applications/Remarkable Sidekick.app/Contents/Resources/app.asar/build/main.bundle.js:28175:27)
at IpcMainImpl.handleIPCMessage (/Applications/Remarkable Sidekick.app/Contents/Resources/app.asar/build/main.bundle.js:28066:13)
at IpcMainImpl.emit (events.js:315:20)
at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)
at Object.emit (events.js:315:20)
```

the image I choose:

![raptor-engine-rm2-sleep-screen](https://user-images.githubusercontent.com/15964/154310383-b0112663-ab29-4f02-a940-21fe29a70d2f.png)

[reddit source](https://www.reddit.com/r/RemarkableTablet/comments/qc9hwq/my_new_spacex_raptor_engine_sleep_screen_for/)

**Comment by lasergoat** [comment]
I read the error and decided to manually add the file into the dir it's complaining about..

That worked - I duplicated the file into `/Users/me/Library/Application\ Support/remarkable-sidekick/local_images`

and then dragged it in again.

unfortunately, it didn't change the sleep screen.

I'll have to just do it manually with ssh.
